"""rename department

Revision ID: 96f0554ef7fe
Revises: 50ba6b7b3b9c
Create Date: 2025-06-11 14:43:17.428422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96f0554ef7fe'
down_revision = '50ba6b7b3b9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###
